name: build
on:
  push:
    branches:
      - master
      - main

env: # Change this if needed
  quarto_file: published-elmasri-optimal
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  computorticle:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Installing dependencies with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true

      - name: Installing quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: register tinytex globally for diagram.lua
        run: |
          mkdir -p ~/.local/bin
          ~/.TinyTeX/bin/x86_64-linux/tlmgr option sys_bin ~/.local/bin
          ~/.TinyTeX/bin/x86_64-linux/tlmgr path add
          ~/.TinyTeX/bin/x86_64-linux/tlmgr install libertinus-fonts
  
      - name: Install Computo extension for Quarto
        run: |
            quarto add --no-prompt computorg/computo-quarto-extension

      - name: Rendering with Quarto
        shell: bash -l {0}
        run: |
            quarto render ${{ env.quarto_file }}.qmd
            mkdir _build
            mv ${{ env.quarto_file }}.html _build/index.html
            mv -vf ${{ env.quarto_file }}_files figures ${{ env.quarto_file }}.pdf _build/
            cp environment.yml _build/
            touch _build/.nojekyll

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true
